- job_name: "node-exporter"
  scrape_interval: 30s
  dns_sd_configs:
  - names:
    - "q-s4.*.bosh"
    type: "A"
    port: 9100
- job_name: "bosh"
  scrape_interval: 2m
  scrape_timeout: 1m
  dns_sd_configs:
  - names:
    - "q-s4.uaa-db.*.cfcr.bosh"
    type: "A"
    port: 9190
- job_name: "postgres"
  dns_sd_configs:
  - names:
    - "q-s4.uaa-db.*.cfcr.bosh"
    type: "A"
    port: 9187
# - job_name: "wavefront-proxy"
#   scrape_interval: 30s
#   scrape_timeout: 10s
#   metrics_path: /actuator/prometheus
#   scheme: https
#   static_configs:
#   - targets:
#     - wavefront-proxy-exporter.cfapps.io:443
- job_name: "zipkin"
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: https
  static_configs:
  - targets:
    - zipkin.dev.ik.am:443

