apiVersion: v1
data:
  prometheus-additional.yml: LSBqb2JfbmFtZTogIm5vZGUtZXhwb3J0ZXIiCiAga3ViZXJuZXRlc19zZF9jb25maWdzOgogIC0gcm9sZTogbm9kZQogIGJlYXJlcl90b2tlbl9maWxlOiAvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvdG9rZW4KICByZWxhYmVsX2NvbmZpZ3M6CiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9hZGRyZXNzX0ludGVybmFsSVBdCiAgICB0YXJnZXRfbGFiZWw6IF9fYWRkcmVzc19fCiAgICByZWdleDogKC4qKQogICAgcmVwbGFjZW1lbnQ6ICQxOjkxMDAKLSBqb2JfbmFtZTogIndhdmVmcm9udC1wcm94eSIKICBzY3JhcGVfaW50ZXJ2YWw6IDMwcwogIHNjcmFwZV90aW1lb3V0OiAxMHMKICBtZXRyaWNzX3BhdGg6IC9hY3R1YXRvci9wcm9tZXRoZXVzCiAgc2NoZW1lOiBodHRwcwogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czoKICAgIC0gd2F2ZWZyb250LXByb3h5LWV4cG9ydGVyLmNmYXBwcy5pbzo0NDMK
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
