apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgojIFRoZSBkaXJlY3RvcnkgZnJvbSB3aGljaCBub3RpZmljYXRpb24gdGVtcGxhdGVzIGFyZSByZWFkLgp0ZW1wbGF0ZXM6CiMgVGhlIHJvb3Qgbm9kZSBvZiB0aGUgcm91dGluZyB0cmVlCnJvdXRlOgogIHJlY2VpdmVyOiBkZWZhdWx0CiAgIyBDaGlsZCByb3V0ZXMKICByb3V0ZXM6IFtdCiMgQSBsaXN0IG9mIG5vdGlmaWNhdGlvbiByZWNlaXZlcnMKcmVjZWl2ZXJzOiBbeyJuYW1lIjoiZGVmYXVsdCIsInNsYWNrX2NvbmZpZ3MiOlt7ImFwaV91cmwiOiJodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9UMVNVMTc1SDgvQjc5MjlBS05IL1RYdDdvOENNWG5TOEpLbnU2QXZLUXBRVyIsICJjaGFubmVsIjoiYWxlcnQiLCAic2VuZF9yZXNvbHZlZCI6dHJ1ZX1dfV0=
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
